package main

import (
	"path/filepath"
)

func defaultConfig() Config {
	return Config{
		ListenAddr:                          defaultListenAddr,
		StatusAddr:                          defaultStatusAddr,
		StatusTLSAddr:                       defaultStatusTLSAddr,
		StatusTagline:                       defaultStatusTagline,
		FiatCurrency:                        defaultFiatCurrency,
		DiscordWorkerNotifyThresholdSeconds: defaultDiscordWorkerNotifyThresholdSeconds,
		GitHubURL:                           defaultGitHubURL,
		MempoolAddressURL:                   defaultMempoolAddressURL,
		StratumTLSListen:                    defaultStratumTLSListen,
		StratumPasswordEnabled:              false,
		StratumPassword:                     "",
		StratumPasswordPublic:               false,
		ClerkIssuerURL:                      defaultClerkIssuerURL,
		ClerkJWKSURL:                        defaultClerkJWKSURL,
		ClerkSignInURL:                      defaultClerkSignInURL,
		ClerkCallbackPath:                   defaultClerkCallbackPath,
		ClerkFrontendAPIURL:                 "",
		ClerkSessionCookieName:              defaultClerkSessionCookieName,
		ClerkSessionAudience:                "",
		ClerkSecretKey:                      "",
		ClerkPublishableKey:                 "",
		RPCURL:                              defaultRPCURL,
		PoolEntropy:                         generatePoolEntropy(),
		PoolFeePercent:                      defaultPoolFeePercent,
		OperatorDonationPercent:             defaultOperatorDonationPercent,
		Extranonce2Size:                     defaultExtranonce2Size,
		TemplateExtraNonce2Size:             defaultTemplateExtraNonce2Size,
		JobEntropy:                          defaultJobEntropy,
		CoinbaseMsg:                         poolSoftwareName,
		CoinbaseScriptSigMaxBytes:           defaultCoinbaseScriptSigMaxBytes,
		ZMQHashBlockAddr:                    defaultZMQHashBlockAddr,
		ZMQRawBlockAddr:                     defaultZMQRawBlockAddr,
		BackblazeBackupIntervalSeconds:      defaultBackblazeBackupIntervalSeconds,
		BackblazeKeepLocalCopy:              true,
		BackblazeForceEveryInterval:         false,
		DataDir:                             defaultDataDir,
		MaxConns:                            defaultMaxConns,
		MaxAcceptsPerSecond:                 defaultMaxAcceptsPerSecond,
		MaxAcceptBurst:                      defaultMaxAcceptBurst,
		AutoAcceptRateLimits:                defaultAutoAcceptRateLimits,
		AcceptReconnectWindow:               defaultAcceptReconnectWindow,
		AcceptBurstWindow:                   defaultAcceptBurstWindow,
		AcceptSteadyStateWindow:             defaultAcceptSteadyStateWindow,
		AcceptSteadyStateRate:               defaultAcceptSteadyStateRate,
		AcceptSteadyStateReconnectPercent:   defaultAcceptSteadyStateReconnectPercent,
		AcceptSteadyStateReconnectWindow:    defaultAcceptSteadyStateReconnectWindow,
		StratumMessagesPerMinute:            defaultStratumMessagesPerMinute,
		MaxRecentJobs:                       defaultRecentJobs,
		ConnectionTimeout:                   defaultConnectionTimeout,
		VersionMask:                         defaultVersionMask,
		MinVersionBits:                      defaultMinVersionBits,
		IgnoreMinVersionBits:                true,
		MaxDifficulty:                       defaultMaxDifficulty,
		MinDifficulty:                       defaultMinDifficulty,
		DefaultDifficulty:                   0,
		TargetSharesPerMin:                  defaultVarDiffTargetSharesPerMin,
		DifficultyStepGranularity:           defaultDifficultyStepGranularity,
		EnforceSuggestedDifficultyLimits:    false,
		HashrateEMATauSeconds:               defaultHashrateEMATauSeconds,
		NTimeForwardSlackSeconds:            defaultNTimeForwardSlackSeconds,
		CleanExpiredBansOnStartup:           true,
		LogLevel:                            "warn",
		RelaxedSubmitValidation:             true,
		SubmitWorkerNameMatch:               false,
		BanInvalidSubmissionsAfter:          defaultBanInvalidSubmissionsAfter,
		BanInvalidSubmissionsWindow:         defaultBanInvalidSubmissionsWindow,
		BanInvalidSubmissionsDuration:       defaultBanInvalidSubmissionsDuration,
		ReconnectBanThreshold:               defaultReconnectBanThreshold,
		ReconnectBanWindowSeconds:           defaultReconnectBanWindowSeconds,
		ReconnectBanDurationSeconds:         defaultReconnectBanDurationSeconds,
		PeerCleanupEnabled:                  defaultPeerCleanupEnabled,
		PeerCleanupMaxPingMs:                defaultPeerCleanupMaxPingMs,
		PeerCleanupMinPeers:                 defaultPeerCleanupMinPeers,
	}
}

func defaultConfigPath() string {
	return filepath.Join(defaultDataDir, "config", "config.toml")
}
