// +build ignore

// This is a helper program to generate valid Bitcoin addresses using BTCD
// Run with: go run generate_test_addresses.go

package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"

	"github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/btcutil"
	"github.com/btcsuite/btcd/chaincfg"
	"github.com/btcsuite/btcd/txscript"
)

func main() {
	params := &chaincfg.MainNetParams

	// Generate some private keys and derive addresses
	fmt.Println("# Valid Bitcoin Test Addresses Generated by BTCD")
	fmt.Println()

	// Generate 5 different taproot addresses
	fmt.Println("## Taproot (P2TR) Addresses:")
	for i := 1; i <= 5; i++ {
		privKey, err := btcec.NewPrivateKey()
		if err != nil {
			panic(err)
		}

		// For taproot, we use the x-only public key
		pubKey := privKey.PubKey()
		taprootKey := txscript.ComputeTaprootKeyNoScript(pubKey)

		addr, err := btcutil.NewAddressTaproot(taprootKey.SerializeCompressed()[1:], params)
		if err != nil {
			panic(err)
		}

		script, err := txscript.PayToAddrScript(addr)
		if err != nil {
			panic(err)
		}

		fmt.Printf("  Address %d: %s\n", i, addr.EncodeAddress())
		fmt.Printf("    Script: %s\n", hex.EncodeToString(script))
		fmt.Printf("    Pubkey: %s\n", hex.EncodeToString(taprootKey.SerializeCompressed()[1:]))
		fmt.Println()
	}

	// Generate P2WPKH addresses
	fmt.Println("## P2WPKH (Native SegWit) Addresses:")
	for i := 1; i <= 3; i++ {
		privKey, err := btcec.NewPrivateKey()
		if err != nil {
			panic(err)
		}

		pubKey := privKey.PubKey()
		pubKeyHash := btcutil.Hash160(pubKey.SerializeCompressed())

		addr, err := btcutil.NewAddressWitnessPubKeyHash(pubKeyHash, params)
		if err != nil {
			panic(err)
		}

		script, err := txscript.PayToAddrScript(addr)
		if err != nil {
			panic(err)
		}

		fmt.Printf("  Address %d: %s\n", i, addr.EncodeAddress())
		fmt.Printf("    Script: %s\n", hex.EncodeToString(script))
		fmt.Println()
	}

	// Generate P2PKH addresses
	fmt.Println("## P2PKH (Legacy) Addresses:")
	for i := 1; i <= 3; i++ {
		privKey, err := btcec.NewPrivateKey()
		if err != nil {
			panic(err)
		}

		pubKey := privKey.PubKey()
		pubKeyHash := btcutil.Hash160(pubKey.SerializeCompressed())

		addr, err := btcutil.NewAddressPubKeyHash(pubKeyHash, params)
		if err != nil {
			panic(err)
		}

		script, err := txscript.PayToAddrScript(addr)
		if err != nil {
			panic(err)
		}

		fmt.Printf("  Address %d: %s\n", i, addr.EncodeAddress())
		fmt.Printf("    Script: %s\n", hex.EncodeToString(script))
		fmt.Println()
	}

	// Generate P2SH addresses (using simple multisig as example)
	fmt.Println("## P2SH (Script Hash) Addresses:")
	for i := 1; i <= 3; i++ {
		// Create a simple 1-of-1 multisig as the redeemScript
		privKey, err := btcec.NewPrivateKey()
		if err != nil {
			panic(err)
		}

		pubKey := privKey.PubKey()
		redeemScript, err := txscript.NewScriptBuilder().
			AddOp(txscript.OP_1).
			AddData(pubKey.SerializeCompressed()).
			AddOp(txscript.OP_1).
			AddOp(txscript.OP_CHECKMULTISIG).
			Script()
		if err != nil {
			panic(err)
		}

		scriptHash := btcutil.Hash160(redeemScript)
		addr, err := btcutil.NewAddressScriptHash(scriptHash, params)
		if err != nil {
			panic(err)
		}

		script, err := txscript.PayToAddrScript(addr)
		if err != nil {
			panic(err)
		}

		fmt.Printf("  Address %d: %s\n", i, addr.EncodeAddress())
		fmt.Printf("    Script: %s\n", hex.EncodeToString(script))
		fmt.Println()
	}

	// Generate P2WSH addresses
	fmt.Println("## P2WSH (Witness Script Hash) Addresses:")
	for i := 1; i <= 2; i++ {
		// Create a simple witness script
		privKey, err := btcec.NewPrivateKey()
		if err != nil {
			panic(err)
		}

		pubKey := privKey.PubKey()
		witnessScript, err := txscript.NewScriptBuilder().
			AddOp(txscript.OP_1).
			AddData(pubKey.SerializeCompressed()).
			AddOp(txscript.OP_1).
			AddOp(txscript.OP_CHECKMULTISIG).
			Script()
		if err != nil {
			panic(err)
		}

		hash1 := sha256.Sum256(witnessScript)
		hash2 := sha256.Sum256(hash1[:])
		scriptHash := hash2[:]
		addr, err := btcutil.NewAddressWitnessScriptHash(scriptHash, params)
		if err != nil {
			panic(err)
		}

		script, err := txscript.PayToAddrScript(addr)
		if err != nil {
			panic(err)
		}

		fmt.Printf("  Address %d: %s\n", i, addr.EncodeAddress())
		fmt.Printf("    Script: %s\n", hex.EncodeToString(script))
		fmt.Println()
	}
}
